Repository neurobagel/federation-api, pull requests merged in 2024-10, with the labels that each got.

#114 [MNT] Removed build docker nightly workflow file
  .github/workflows/build_docker.yaml
Labels: pr-internal

#119 [FIX] Docs link
  README.md
Labels: pr-documentation

#121 [ENH] Implemented `pipeline_name` and `pipeline_version` query params
  app/api/crud.py
  app/api/models.py
  app/api/routers/query.py
  tests/conftest.py
Labels: pr-minor-breaking

#125 [ENH] Add route for fetching available versions of a pipeline across n-APIs
  app/api/crud.py
  app/api/routers/pipelines.py
  app/api/utility.py
  app/main.py
  tests/test_pipelines.py
Labels: pr-minor

#129 [FIX] Allow only `"true"` or `None` for `is_control` query parameter
  app/api/crud.py
  app/api/models.py
  tests/test_query.py
Labels: release, pr-bug-fix

#132 [FIX] Ensure Google auth token is forwarded in request to n-API
  app/api/crud.py
  app/api/routers/query.py
  app/api/utility.py
Labels: release, pr-patch
