Repository neurobagel/federation-api, pull requests merged in 2024-02, with the labels that each got.

#67 [FIX] Handle empty local nodes file
  app/api/utility.py
  tests/test_utility.py
Labels: pr-bug-fix

#65 [ENH] Support partial term fetching failures
  app/api/crud.py
  app/api/models.py
  app/api/routers/attributes.py
  app/api/routers/query.py
  tests/conftest.py
  tests/test_attributes.py
  tests/test_query.py
Labels: pr-minor-breaking

#71 [DOC] Update Copyright holders
  LICENSE
Labels: skip-release
