Repository neurobagel/federation-api, pull requests merged in 2024-01, with the labels that each got.

#56 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/pull_request_template.md
  .github/workflows/release.yaml
  .github/workflows/stale.yml
Labels: _bot

#57 [CI] Stop pre-commit auto-fixing PRs
  .pre-commit-config.yaml
Labels: skip-release

#59 [CI] Update image tag for default build
  .github/workflows/build_docker.yaml
Labels: skip-release

#58 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/workflows/build_docker_on_release.yml
Labels: _bot

#64 [ENH] split session query parameter into phenotypic + imaging
  app/api/crud.py
  app/api/models.py
  app/api/routers/query.py
  tests/test_query.py
Labels: pr-minor-breaking
