Repository neurobagel/federation-api, pull requests merged in 2024-12, with the labels that each got.

#139 [REF] Manually verify ID token using PyJWT instead of google_auth
  app/api/crud.py
  app/api/routers/query.py
  app/api/security.py
  requirements.txt
  tests/conftest.py
  tests/test_query.py
  tests/test_security.py
Labels: release, pr-internal

#141 [ENH] Add consistent badges
  README.md
Labels: pr-internal

#143 [MNT] Update labels & rename dependabot.yaml to dependabot.yml
  .github/dependabot.yml
Labels: skip-release
