Repository neurobagel/federation-api, pull requests merged in 2024-06, with the labels that each got.

#94 [MNT] Set default timeout to `None`
  app/api/utility.py
Labels: release, pr-patch

#99 [MNT] Add welcome page at /
  app/main.py
  tests/test_attributes.py
Labels: pr-patch

#100 🔄 synced file(s) with neurobagel/workflows
  .autorc
Labels: _bot

#98 [FIX] Explicitly check that `local_nb_nodes.json` is an existing file
  app/api/utility.py
  tests/test_nodes.py
Labels: release, pr-bug-fix
